version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
    privileged: true
    shm_size: '512m'
    volumes:
        - "app:/app"
        - "code_config:/code_config"
    #network_mode: "host"
volumes:
  app:
  code_config:
